### ISSUE TITLE
Add docker-stack.yml

### ISSUE THREAD

**Issue by JinnaBalu** [JinnaBalu/docker-minio#4]
- Add the docker-stack.yml with 

```yml
version: '3'

services:
 minio1:
  image: minio/minio
  volumes:
   - sample1:/export
  ports:
   - "9001:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: TestACCESSKeY
   MINIO_SECRET_KEY: TESTSeCRetKeY
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio2:
  image: minio/minio
  volumes:
   - sample2:/export
  ports:
   - "9002:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: TestACCESSKeY
   MINIO_SECRET_KEY: TESTSeCRetKeY
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio3:
  image: minio/minio
  volumes:
   - sample3:/export
  ports:
   - "9003:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: TestACCESSKeY
   MINIO_SECRET_KEY: TESTSeCRetKeY
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

 minio4:
  image: minio/minio
  volumes:
   - sample4:/export
  ports:
   - "9004:9000"
  networks:
   - minio_distributed
  environment:
   MINIO_ACCESS_KEY: TestACCESSKeY
   MINIO_SECRET_KEY: TESTSeCRetKeY
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

volumes:
  sample1:
  sample2:
  sample3:
  sample4:

networks:
 minio_distributed:
  driver: overlay

```
